# Generated by Django 2.2.4 on 2019-10-21 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=100)),
                ('content_title', models.CharField(max_length=100)),
                ('monster_name', models.CharField(max_length=100)),
                ('monster_image', imagekit.models.fields.ProcessedImageField(upload_to='monster')),
                ('monster_detail', models.CharField(max_length=100)),
                ('monster_size', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monster.Monster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
