# Generated by Django 2.2.4 on 2019-08-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=50)),
                ('replace', models.CharField(max_length=50)),
                ('img_url', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
    ]
